### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [cgolobic/FlightReservationSystem#1]
you must not re-create `QueryFile` ever, it is to be created once only! Otherwise you end up re-reading the file on every request, which is horrible.

See [QueryFile API](http://vitaly-t.github.io/pg-promise/QueryFile.html) for an example.

**Comment by cgolobic** [comment]
Thanks for pointing that out, I've fixed the issue.  Also, thank you for creating, maintaining, and documenting the pg-promise library.  It has been easy to use and has great documentation!
